-- Schéma V4 de base pour Supabase/PostgreSQL
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  pilot_code text unique not null,
  name text not null,
  simbrief text default '',
  rank text not null default 'Cadet',
  role text not null default 'pilot' check (role in ('pilot','staff','admin')),
  hours numeric not null default 0,
  flights integer not null default 0,
  miles integer not null default 0,
  xp integer not null default 0,
  created_at timestamptz not null default now()
);
create table if not exists public.flights (
  id bigint generated by default as identity primary key,
  flight_number text unique not null,
  flight_date date not null,
  departure text not null,
  arrival text not null,
  aircraft text not null,
  altitude text default '',
  active boolean not null default true
);
create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  flight_id bigint not null references public.flights(id) on delete cascade,
  status text not null default 'reserved' check (status in ('reserved','cancelled','completed')),
  created_at timestamptz not null default now(),
  unique(user_id, flight_id)
);
create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  flight_number text not null,
  report_date date not null,
  departure text not null,
  arrival text not null,
  aircraft text not null,
  duration numeric not null default 0,
  distance integer not null default 0,
  status text not null default 'pending' check (status in ('pending','validated','rejected')),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.flights enable row level security;
alter table public.bookings enable row level security;
alter table public.reports enable row level security;

create policy "public can read active flights" on public.flights for select using (active = true);
create policy "pilot reads own profile" on public.profiles for select using (auth.uid() = id);
create policy "pilot updates own profile" on public.profiles for update using (auth.uid() = id);
create policy "pilot reads own bookings" on public.bookings for select using (auth.uid() = user_id);
create policy "pilot creates own bookings" on public.bookings for insert with check (auth.uid() = user_id);
create policy "pilot updates own bookings" on public.bookings for update using (auth.uid() = user_id);
create policy "pilot reads own reports" on public.reports for select using (auth.uid() = user_id);
create policy "pilot creates own reports" on public.reports for insert with check (auth.uid() = user_id);
