const $=s=>document.querySelector(s);
const DB_KEY='va-v2-db';
const SESSION_KEY='va-v2-session';
const WALL_KEY='va-wallpaper';
const seed={users:[{id:'PIL001',name:'Sébastien',email:'demo@virtualairlines.local',password:'demo123',simbrief:'',rank:'Commandant de bord',hours:184,flights:42,miles:27650}],reports:[{id:'RPT001',userId:'PIL001',flight:'VA342',date:'2026-10-02',from:'LFPG',to:'CYUL',aircraft:'B789',duration:7.2,status:'Validé'}],bookings:[]};
function db(){try{return JSON.parse(localStorage.getItem(DB_KEY))||seed}catch{return seed}}
function saveDB(x){localStorage.setItem(DB_KEY,JSON.stringify(x))}
if(!localStorage.getItem(DB_KEY)) saveDB(seed);
function session(){const id=localStorage.getItem(SESSION_KEY);return db().users.find(u=>u.id===id)||null}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function tick(){const d=new Date(),utc=d.toISOString().slice(11,16),local=d.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'});document.querySelectorAll('[data-utc]').forEach(e=>e.textContent=utc+' UTC');document.querySelectorAll('[data-local]').forEach(e=>e.textContent=local)} setInterval(tick,1000);tick();
function applyUser(){const u=session();document.querySelectorAll('[data-user-name]').forEach(e=>e.textContent=u?u.name:'Visiteur');document.querySelectorAll('[data-auth]').forEach(e=>e.innerHTML=u?`<span class="badge">${escapeHtml(u.rank)}</span> <button class="btn secondary" type="button" data-logout>Déconnexion</button>`:`<a class="btn" href="connexion.html">Connexion</a>`);document.querySelectorAll('[data-logout]').forEach(b=>b.onclick=()=>{localStorage.removeItem(SESSION_KEY);location.href='index.html'});return u}
applyUser();
document.querySelectorAll('[data-wall]').forEach(x=>x.addEventListener('click',()=>{localStorage.setItem(WALL_KEY,x.dataset.wall);document.body.style.backgroundImage=`url("${x.dataset.wall}")`}));const savedWall=localStorage.getItem(WALL_KEY);if(savedWall)document.body.style.backgroundImage=`url("${savedWall}")`;
function notice(el,msg,ok=false){if(!el)return;el.className='notice '+(ok?'success':'');el.textContent=msg}
const register=$('#registerForm');if(register)register.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(register),name=f.get('name').trim(),email=f.get('email').trim().toLowerCase(),password=f.get('password'),simbrief=f.get('simbrief').trim();const d=db();if(d.users.some(u=>u.email===email))return notice($('#registerMsg'),'Cette adresse est déjà utilisée.');const id='PIL'+String(d.users.length+1).padStart(3,'0');d.users.push({id,name,email,password,simbrief,rank:'Cadet',hours:0,flights:0,miles:0});saveDB(d);localStorage.setItem(SESSION_KEY,id);notice($('#registerMsg'),`Compte créé. Bienvenue ${name} !`,true);setTimeout(()=>location.href='espace-pilote.html',600)});
const login=$('#loginForm');if(login)login.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(login),email=f.get('email').trim().toLowerCase(),password=f.get('password'),u=db().users.find(x=>x.email===email&&x.password===password);if(!u)return notice($('#loginMsg'),'E-mail ou mot de passe incorrect.');localStorage.setItem(SESSION_KEY,u.id);location.href='espace-pilote.html'});
const simForm=$('#simbriefForm');if(simForm)simForm.addEventListener('submit',e=>{e.preventDefault();const u=session(),f=new FormData(simForm),from=f.get('from').trim().toUpperCase(),to=f.get('to').trim().toUpperCase(),ac=f.get('aircraft'),out=$('#simOut');if(!from||!to)return notice(out,'Renseigne le départ et l’arrivée.');if(u&&f.get('simbrief')){const d=db(),x=d.users.find(a=>a.id===u.id);x.simbrief=f.get('simbrief').trim();saveDB(d)}out.innerHTML=`<b>${from} → ${to}</b> · ${escapeHtml(ac)}<br><small>Préparation V2 enregistrée. L’appel API SimBrief réel sera branché au serveur.</small>`;out.className='notice success'});
const report=$('#reportForm');if(report)report.addEventListener('submit',e=>{e.preventDefault();const u=session();if(!u)return notice($('#reportMsg'),'Connecte-toi avant d’envoyer un rapport.');const f=new FormData(report),d=db();const duration=Number(f.get('duration'))||0;d.reports.unshift({id:'RPT'+Date.now(),userId:u.id,flight:f.get('flight').toUpperCase(),date:f.get('date'),from:f.get('from').toUpperCase(),to:f.get('to').toUpperCase(),aircraft:f.get('aircraft'),duration,status:'En attente'});const x=d.users.find(a=>a.id===u.id);x.flights+=1;x.hours=Number((x.hours+duration).toFixed(1));x.miles+=Math.round(duration*500);saveDB(d);notice($('#reportMsg'),'Rapport enregistré. Il est maintenant en attente de validation.',true);report.reset();renderReports()});
function renderReports(){const body=$('#myReports');if(!body)return;const u=session();if(!u){body.innerHTML='<tr><td colspan="7">Connecte-toi pour voir tes rapports.</td></tr>';return}const rows=db().reports.filter(r=>r.userId===u.id);body.innerHTML=rows.length?rows.map(r=>`<tr><td>${escapeHtml(r.flight)}</td><td>${escapeHtml(r.date)}</td><td>${escapeHtml(r.from)} → ${escapeHtml(r.to)}</td><td>${escapeHtml(r.aircraft)}</td><td>${r.duration} h</td><td><span class="badge">${escapeHtml(r.status)}</span></td><td>${r.id}</td></tr>`).join(''):'<tr><td colspan="7">Aucun rapport pour le moment.</td></tr>'}
function renderDashboard(){const u=applyUser();if(!u)return;document.querySelectorAll('[data-stat-hours]').forEach(e=>e.textContent=u.hours+' h');document.querySelectorAll('[data-stat-flights]').forEach(e=>e.textContent=u.flights);document.querySelectorAll('[data-stat-miles]').forEach(e=>e.textContent=u.miles.toLocaleString('fr-FR'));document.querySelectorAll('[data-rank]').forEach(e=>e.textContent=u.rank);document.querySelectorAll('[data-profile-name]').forEach(e=>e.textContent=u.name);document.querySelectorAll('[data-profile-email]').forEach(e=>e.textContent=u.email);document.querySelectorAll('[data-profile-simbrief]').forEach(e=>e.value=u.simbrief||'')}
renderDashboard();renderReports();
async function loadVatsim(){const box=$('#vatsimStatus');if(!box)return;try{const r=await fetch('https://data.vatsim.net/v3/vatsim-data.json');const d=await r.json();box.textContent=`VATSIM : ${d.pilots.length} pilotes · ${d.controllers.length} contrôleurs en ligne`;const tbody=$('#pilotRows');if(tbody)tbody.innerHTML=d.pilots.slice(0,40).map(p=>`<tr><td>${escapeHtml(p.callsign||'-')}</td><td>${escapeHtml(p.name||'-')}</td><td>${escapeHtml(p.flight_plan?.departure||'-')}</td><td>${escapeHtml(p.flight_plan?.arrival||'-')}</td><td>${p.altitude||'-'}</td></tr>`).join('')}catch(e){box.textContent='VATSIM indisponible depuis ce navigateur. L’intégration serveur sera ajoutée dans une prochaine étape.'}}
loadVatsim();
