const VA_DB='va-v4-demo-db';
const VA_SESSION='va-v4-session';
const seedV4={users:[{id:'PIL001',name:'Sébastien',email:'demo@virtualairlines.local',password:'demo123',simbrief:'',rank:'Commandant de bord',hours:342,flights:48,miles:184560,xp:1240,role:'pilot'}],reports:[{id:'RPT001',userId:'PIL001',flight:'VA342',date:'2026-10-02',from:'LFPG',to:'CYUL',aircraft:'B789',duration:7.2,distance:3440,status:'Validé'}],bookings:[{id:'BKG001',userId:'PIL001',flight:'VA458',date:'2026-10-06',from:'LFPG',to:'KJFK',aircraft:'A359',status:'Réservé'}],news:[{title:'V4 ouverte en prévisualisation',date:'03 oct. 2026',tag:'Projet'},{title:'Live Map VATSIM améliorée',date:'02 oct. 2026',tag:'Réseau'},{title:'Nouveau programme long-courrier',date:'30 sept. 2026',tag:'VA'}]};
function v4db(){try{return JSON.parse(localStorage.getItem(VA_DB))||structuredClone(seedV4)}catch{return structuredClone(seedV4)}}
function saveV4(d){localStorage.setItem(VA_DB,JSON.stringify(d))}
if(!localStorage.getItem(VA_DB))saveV4(seedV4);
function currentUser(){const id=localStorage.getItem(VA_SESSION);return v4db().users.find(u=>u.id===id)||null}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function msg(el,text,ok=false){if(el){el.className='notice '+(ok?'success':'');el.textContent=text}}
function syncUser(){const u=currentUser();document.querySelectorAll('[data-user-name]').forEach(e=>e.textContent=u?.name||'Visiteur');document.querySelectorAll('[data-auth]').forEach(e=>e.innerHTML=u?`<span class="badge">${esc(u.rank)}</span> <button class="btn secondary" data-v4-logout>Déconnexion</button>`:`<a class="btn" href="connexion.html">Connexion</a>`);document.querySelectorAll('[data-v4-logout]').forEach(b=>b.onclick=()=>{localStorage.removeItem(VA_SESSION);location.href='index.html'});return u}
function clocks(){const d=new Date();document.querySelectorAll('[data-utc]').forEach(e=>e.textContent=d.toISOString().slice(11,16)+' UTC');document.querySelectorAll('[data-local]').forEach(e=>e.textContent=d.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}))}setInterval(clocks,1000);clocks();syncUser();
function protect(){if(document.body.dataset.auth==='required'&&!currentUser())location.href='connexion.html'}protect();
const login=document.querySelector('#loginForm');if(login)login.onsubmit=e=>{e.preventDefault();const f=new FormData(login),email=f.get('email').trim().toLowerCase(),password=f.get('password'),d=v4db(),u=d.users.find(x=>x.email===email&&x.password===password);if(!u)return msg(document.querySelector('#loginMsg'),'E-mail ou mot de passe incorrect.');localStorage.setItem(VA_SESSION,u.id);location.href='espace-pilote.html'};
const register=document.querySelector('#registerForm');if(register)register.onsubmit=e=>{e.preventDefault();const f=new FormData(register),d=v4db(),email=f.get('email').trim().toLowerCase();if(d.users.some(x=>x.email===email))return msg(document.querySelector('#registerMsg'),'Cette adresse est déjà utilisée.');const u={id:'PIL'+String(d.users.length+1).padStart(3,'0'),name:f.get('name').trim(),email,password:f.get('password'),simbrief:f.get('simbrief')?.trim()||'',rank:'Cadet',hours:0,flights:0,miles:0,xp:0,role:'pilot'};d.users.push(u);saveV4(d);localStorage.setItem(VA_SESSION,u.id);msg(document.querySelector('#registerMsg'),'Compte créé. Bienvenue dans la compagnie !',true);setTimeout(()=>location.href='espace-pilote.html',400)};
function renderUserStats(){const u=currentUser();if(!u)return;document.querySelectorAll('[data-stat-hours]').forEach(e=>e.textContent=u.hours+' h');document.querySelectorAll('[data-stat-flights]').forEach(e=>e.textContent=u.flights);document.querySelectorAll('[data-stat-miles]').forEach(e=>e.textContent=u.miles.toLocaleString('fr-FR'));document.querySelectorAll('[data-rank]').forEach(e=>e.textContent=u.rank);document.querySelectorAll('[data-xp]').forEach(e=>e.textContent=u.xp+' XP');document.querySelectorAll('[data-profile-name]').forEach(e=>e.textContent=u.name);document.querySelectorAll('[data-profile-email]').forEach(e=>e.textContent=u.email)}renderUserStats();
function renderBookings(){const u=currentUser(),tbody=document.querySelector('#bookingRows');if(!tbody)return;const rows=v4db().bookings.filter(b=>!u||b.userId===u.id);tbody.innerHTML=rows.length?rows.map(b=>`<tr><td>${esc(b.date)}</td><td><b>${esc(b.flight)}</b></td><td>${esc(b.from)} → ${esc(b.to)}</td><td>${esc(b.aircraft)}</td><td><span class="badge">${esc(b.status)}</span></td><td><button class="filter" data-cancel="${b.id}">Annuler</button></td></tr>`).join(''):'<tr><td colspan="6">Aucune réservation.</td></tr>';tbody.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>{const d=v4db();d.bookings=d.bookings.filter(x=>x.id!==b.dataset.cancel);saveV4(d);renderBookings();msg(document.querySelector('#bookingMsg'),'Réservation annulée.',true)})}
function setupBookings(){document.querySelectorAll('[data-book-flight]').forEach(b=>b.onclick=()=>{const u=currentUser();if(!u)return location.href='connexion.html';const d=v4db();if(d.bookings.some(x=>x.userId===u.id&&x.flight===b.dataset.bookFlight))return msg(document.querySelector('#bookingMsg'),'Ce vol est déjà réservé.');d.bookings.push({id:'BKG'+Date.now(),userId:u.id,flight:b.dataset.bookFlight,date:b.dataset.date,from:b.dataset.from,to:b.dataset.to,aircraft:b.dataset.aircraft,status:'Réservé'});saveV4(d);msg(document.querySelector('#bookingMsg'),'Vol réservé avec succès.',true);renderBookings()})}setupBookings();renderBookings();
const report=document.querySelector('#reportForm');if(report)report.onsubmit=e=>{e.preventDefault();const u=currentUser();if(!u)return location.href='connexion.html';const f=new FormData(report),d=v4db(),duration=Number(f.get('duration'))||0;d.reports.unshift({id:'RPT'+Date.now(),userId:u.id,flight:f.get('flight').toUpperCase(),date:f.get('date'),from:f.get('from').toUpperCase(),to:f.get('to').toUpperCase(),aircraft:f.get('aircraft'),duration,distance:Math.round(duration*480),status:'En attente'});saveV4(d);msg(document.querySelector('#reportMsg'),'Rapport transmis à l’administration pour validation.',true);report.reset();renderReports()};
function renderReports(){const u=currentUser(),body=document.querySelector('#myReports');if(!body)return;const rows=v4db().reports.filter(r=>!u||r.userId===u.id);body.innerHTML=rows.length?rows.map(r=>`<tr><td>${esc(r.flight)}</td><td>${esc(r.date)}</td><td>${esc(r.from)} → ${esc(r.to)}</td><td>${esc(r.aircraft)}</td><td>${r.duration} h</td><td>${r.distance||'-'} NM</td><td><span class="badge">${esc(r.status)}</span></td></tr>`).join(''):'<tr><td colspan="7">Aucun rapport.</td></tr>'}renderReports();
const sim=document.querySelector('#simbriefForm');if(sim)sim.onsubmit=e=>{e.preventDefault();const f=new FormData(sim),from=f.get('from').toUpperCase(),to=f.get('to').toUpperCase(),ac=f.get('aircraft'),alt=f.get('altitude');if(!from||!to)return msg(document.querySelector('#simOut'),'Départ et arrivée sont obligatoires.');const dist=Math.max(300,Math.round(3200+(to.charCodeAt(0)-from.charCodeAt(0))*37));const hrs=(dist/470+1).toFixed(1);document.querySelector('#simOut').innerHTML=`<b>${from} → ${to}</b><br>Avion : ${esc(ac)} · Niveau : ${esc(alt)} · Distance estimée : ${dist} NM · ETE : ${hrs} h<br><small>Mode V4 démo : le vrai OFP SimBrief sera généré après connexion de l’API.</small>`;document.querySelector('#simOut').className='notice success'};
function admin(){const body=document.querySelector('#adminUsers');if(!body)return;const d=v4db();body.innerHTML=d.users.map(u=>`<tr><td>${esc(u.id)}</td><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td>${esc(u.rank)}</td><td>${u.flights}</td><td>${u.hours} h</td><td>${esc(u.role)}</td></tr>`).join('');document.querySelector('[data-admin-reports]').textContent=d.reports.filter(r=>r.status==='En attente').length;document.querySelector('[data-admin-bookings]').textContent=d.bookings.length;document.querySelector('[data-admin-pilots]').textContent=d.users.length}admin();
